package com.app.phew.network

object Urls {
    const val ENDPOINT_GOOGLE = "https://maps.googleapis.com/maps/api/"
    const val ENDPOINT = "https://phew.orabi.rmal.com.sa/api/"
    const val MOVIES_END = "https://api.themoviedb.org/3/"

    //Auth
    const val REGISTER = "auth/register"
    const val LOGIN = "auth/login"
    const val SOCIAL_LOGIN = "auth/social_login"
    const val COUNTRIES = "countries"
    const val CITIES = "countries/{id}/cities"
    const val FORGET_PASSWORD = "auth/forgot_password"
    const val VERIFY = "auth/verify"
    const val RESET_PASSWORD = "auth/reset_password"
    const val RESEND_CODE = "auth/resend/code"
    const val UPDATE_PROFILE = "auth/update_profile"
    const val DELETE_IMAGE = "auth/image/{id}"
    const val LOGOUT = "auth/logout"
    const val SEARCH = "search"

    //Main
    const val POSTS = "posts"
    const val POST = "posts/{post_id}"
    const val POST_FINDLAY = "posts/{post_id}/findly"
    const val POST_PRIVACY = "posts/{post_id}/update_privacy"
    const val POST_REACT = "posts/{post_id}/like"
    const val POSTS_FAVORITE = "posts/{post_id}/fav"
    const val NOTIFICATIONS = "notifications"
    const val DELETE_NOTIFICATIONS = "notifications/{notificationId}"
    const val ACCEPT_REQUEST = "users/{userId}/friend_request/accept"
    const val REJECT_REQUEST = "users/{userId}/friend_request/reject"
    const val REQUESTS_LIST = "users/{userId}/friend_request"
    const val CHATS_LIST = "chats"
    const val SECRET_MESSAGE_LIST = "secret_message"
    const val FINDLY_COUNTRIES = "findly/countries"
    const val FINDLY_CITIES = "findly/countries/{id}/cities"
    const val SCREEN_SHOT = "screen_shot"
    const val CHAT_DETAILS = "chats/{userId}"
    const val MOVIES = "movies"
    const val MOVIES_SEARCH = "search/movie"
    const val PLACES_SEARCH = "place/textsearch/json"
    const val FRIENDS = "users/{userId}/friends"
    const val PROFILE = "users/{userId}"
    const val UPDATE_SETTING = "auth/update_setting"
    const val UPDATE_PACKAGE_SETTINGS = "auth/update_package_setting"
    const val ABOUT_APP = "settings/about"
    const val TERMS = "settings/conditions_terms"
    const val FOLLOW_US = "settings/social_info"
    const val EDIT_PASSWORD = "auth/update_password"
    const val FOLLOW = "users/{id}/follow"
    const val SEND_REQUEST = "users/{id}/friend_request/send"
    const val CANCEL_REQUEST = "users/{id}/friend_request/cancel"
    const val PROFILE_POSTS = "users/{id}/posts?type="
    const val PACKAGEE = "packages"
    const val SUBSCRIBE_PACKAGEE = "auth/subscribe_pacakge/{id}"
    const val POST_COMMENTS = "posts/{id}/comments"
    const val REMOVE_FRIENDS = "users/{userId}/friends/remove"
    const val SEND_SECRET_MESSAGE = "users/{userId}/secret_message"
}